#Postgres version  9.6
default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5
  username: postgres
  password: prader00

development:
  <<: *default
  database: blog_desarrollo

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_produccion
